[
    {
        "content": "<p>I'm struggling with why the exception trace doesn't work, by the ML function <code>Runtime.exn_trace</code>.<br>\nIn this minimal example,</p>\n<div class=\"codehilite\" data-code-language=\"Standard ML\"><pre><span></span><code><span class=\"kr\">fun</span> <span class=\"nf\">f</span> <span class=\"n\">i</span> <span class=\"p\">=</span> <span class=\"kr\">if</span> <span class=\"n\">i</span> <span class=\"p\">=</span> <span class=\"mi\">0</span> <span class=\"kr\">then</span> <span class=\"kr\">raise</span> <span class=\"n\">Fail</span> <span class=\"s2\">\"\"</span> <span class=\"kr\">else</span> <span class=\"n\">f</span> <span class=\"p\">(</span><span class=\"n\">i-</span><span class=\"mi\">1</span><span class=\"p\">)</span>\n<span class=\"kr\">val</span> <span class=\"nv\">x</span> <span class=\"p\">=</span> <span class=\"nn\">Runtime</span><span class=\"p\">.</span><span class=\"n\">exn_trace</span> <span class=\"p\">(</span><span class=\"kr\">fn</span> <span class=\"p\">_</span> <span class=\"p\">=&gt;</span> <span class=\"n\">f</span> <span class=\"mi\">10</span><span class=\"p\">)</span>\n</code></pre></div>\n<p>The output dialogue doesn't print any stack trace as expected, but only a simple error in a line.<br>\nShould I set some other configurations to enable the stack trace?</p>",
        "id": 244513481,
        "sender_full_name": "Qiyuan Xu",
        "timestamp": 1625108639
    },
    {
        "content": "<p>I remember that I had a similar issue in the past where the exception trace wasn't working. I never managed to resolve the issue though. The exception trace needs to be enabled in the Isabelle plugin options but it is enabled by default.</p>",
        "id": 244533462,
        "sender_full_name": "Lukas Stevens",
        "timestamp": 1625127990
    },
    {
        "content": "<p>You may have more luck if you ask about this on the mailing list.</p>",
        "id": 244534216,
        "sender_full_name": "Lukas Stevens",
        "timestamp": 1625128498
    },
    {
        "content": "<p>Oh, thank you. I made it works by enabling options in the setting panel <code>Ctrl+F12/Plugin Options/Isabelle/the section for ML system/ML Debugger and ML Exception Trace</code>. A reboot of the Isabelle is also required to make the setting works. I don't know why they're disabled in my case, but it doesn't matter anymore.</p>",
        "id": 244568526,
        "sender_full_name": "Qiyuan Xu",
        "timestamp": 1625147314
    },
    {
        "content": "<p><span class=\"user-mention silent\" data-user-id=\"233155\">Lukas Stevens</span> <a href=\"#narrow/stream/211483-Isabelle.2FML/topic/stack.20trace.20for.20exceptions/near/244533462\">said</a>:</p>\n<blockquote>\n<p>I remember that I had a similar issue in the past where the exception trace wasn't working. I never managed to resolve the issue though. The exception trace needs to be enabled in the Isabelle plugin options but it is enabled by default.</p>\n</blockquote>\n<p>The part with it being enabled by default might be wrong.</p>",
        "id": 244569146,
        "sender_full_name": "Lukas Stevens",
        "timestamp": 1625147544
    }
]