<html>
<head><meta charset="utf-8"><title>stack trace for exceptions · Isabelle/ML · Zulip Chat Archive</title></head>
<h2>Stream: <a href="http://isabelle.systems/zulip-archive/stream/211483-Isabelle/ML/index.html">Isabelle/ML</a></h2>
<h3>Topic: <a href="http://isabelle.systems/zulip-archive/stream/211483-Isabelle/ML/topic/stack.20trace.20for.20exceptions.html">stack trace for exceptions</a></h3>

<hr>

<base href="https://isabelle.zulipchat.com/">

<head><link href="http://isabelle.systems/zulip-archive/style.css" rel="stylesheet"></head>

<a name="244513481"></a>
<h4><a href="https://isabelle.zulipchat.com/#narrow/stream/211483-Isabelle/ML/topic/stack%20trace%20for%20exceptions/near/244513481" class="zl"><img src="http://isabelle.systems/zulip-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Qiyuan Xu <a href="http://isabelle.systems/zulip-archive/stream/211483-Isabelle/ML/topic/stack.20trace.20for.20exceptions.html#244513481">(Jul 01 2021 at 03:03)</a>:</h4>
<p>I'm struggling with why the exception trace doesn't work, by the ML function <code>Runtime.exn_trace</code>.<br>
In this minimal example,</p>
<div class="codehilite" data-code-language="Standard ML"><pre><span></span><code><span class="kr">fun</span> <span class="nf">f</span> <span class="n">i</span> <span class="p">=</span> <span class="kr">if</span> <span class="n">i</span> <span class="p">=</span> <span class="mi">0</span> <span class="kr">then</span> <span class="kr">raise</span> <span class="n">Fail</span> <span class="s2">""</span> <span class="kr">else</span> <span class="n">f</span> <span class="p">(</span><span class="n">i-</span><span class="mi">1</span><span class="p">)</span>
<span class="kr">val</span> <span class="nv">x</span> <span class="p">=</span> <span class="nn">Runtime</span><span class="p">.</span><span class="n">exn_trace</span> <span class="p">(</span><span class="kr">fn</span> <span class="p">_</span> <span class="p">=&gt;</span> <span class="n">f</span> <span class="mi">10</span><span class="p">)</span>
</code></pre></div>
<p>The output dialogue doesn't print any stack trace as expected, but only a simple error in a line.<br>
Should I set some other configurations to enable the stack trace?</p>



<a name="244533462"></a>
<h4><a href="https://isabelle.zulipchat.com/#narrow/stream/211483-Isabelle/ML/topic/stack%20trace%20for%20exceptions/near/244533462" class="zl"><img src="http://isabelle.systems/zulip-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Lukas Stevens <a href="http://isabelle.systems/zulip-archive/stream/211483-Isabelle/ML/topic/stack.20trace.20for.20exceptions.html#244533462">(Jul 01 2021 at 08:26)</a>:</h4>
<p>I remember that I had a similar issue in the past where the exception trace wasn't working. I never managed to resolve the issue though. The exception trace needs to be enabled in the Isabelle plugin options but it is enabled by default.</p>



<a name="244534216"></a>
<h4><a href="https://isabelle.zulipchat.com/#narrow/stream/211483-Isabelle/ML/topic/stack%20trace%20for%20exceptions/near/244534216" class="zl"><img src="http://isabelle.systems/zulip-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Lukas Stevens <a href="http://isabelle.systems/zulip-archive/stream/211483-Isabelle/ML/topic/stack.20trace.20for.20exceptions.html#244534216">(Jul 01 2021 at 08:34)</a>:</h4>
<p>You may have more luck if you ask about this on the mailing list.</p>



<a name="244568526"></a>
<h4><a href="https://isabelle.zulipchat.com/#narrow/stream/211483-Isabelle/ML/topic/stack%20trace%20for%20exceptions/near/244568526" class="zl"><img src="http://isabelle.systems/zulip-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Qiyuan Xu <a href="http://isabelle.systems/zulip-archive/stream/211483-Isabelle/ML/topic/stack.20trace.20for.20exceptions.html#244568526">(Jul 01 2021 at 13:48)</a>:</h4>
<p>Oh, thank you. I made it works by enabling options in the setting panel <code>Ctrl+F12/Plugin Options/Isabelle/the section for ML system/ML Debugger and ML Exception Trace</code>. A reboot of the Isabelle is also required to make the setting works. I don't know why they're disabled in my case, but it doesn't matter anymore.</p>



<a name="244569146"></a>
<h4><a href="https://isabelle.zulipchat.com/#narrow/stream/211483-Isabelle/ML/topic/stack%20trace%20for%20exceptions/near/244569146" class="zl"><img src="http://isabelle.systems/zulip-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Lukas Stevens <a href="http://isabelle.systems/zulip-archive/stream/211483-Isabelle/ML/topic/stack.20trace.20for.20exceptions.html#244569146">(Jul 01 2021 at 13:52)</a>:</h4>
<p><span class="user-mention silent" data-user-id="233155">Lukas Stevens</span> <a href="#narrow/stream/211483-Isabelle.2FML/topic/stack.20trace.20for.20exceptions/near/244533462">said</a>:</p>
<blockquote>
<p>I remember that I had a similar issue in the past where the exception trace wasn't working. I never managed to resolve the issue though. The exception trace needs to be enabled in the Isabelle plugin options but it is enabled by default.</p>
</blockquote>
<p>The part with it being enabled by default might be wrong.</p>



<hr><p>Last updated: Jul 15 2022 at 23:21 UTC</p>
</html>