[
    {
        "content": "<p>From: Tao Ma &lt;<a href=\"mailto:separable@gmail.com\">separable@gmail.com</a>&gt;<br>\nhi,<br>\ni would like to find out more information when the isabelle gives \"empty<br>\nresult sequence\".<br>\nit seems this exception is raised by a line proof_history.ML, so i tried to<br>\nuse polyml<br>\ndebugger to set a breakpoint, recompile the source adding<br>\nPoly.Compiler.debug := true<br>\nthen in proof general use \"ML {* open PolyML.Debug; breakAt<br>\n(proof_history.ML 70); *}\"<br>\nbut it doesnt seem to work. is there a way to get the stack trace?<br>\nthanks<br>\ntao</p>",
        "id": 294047728,
        "sender_full_name": "Email Gateway",
        "timestamp": 1660818011
    }
]