[
    {
        "content": "<p>From: Peter Lammich &lt;<a href=\"mailto:lammich@in.tum.de\">lammich@in.tum.de</a>&gt;<br>\nHi,</p>\n<p>I can't prove that with hard numbers, but it feels like the frequency<br>\nof messages \"z3: A prover error occurred\" (and also for cvc4) has<br>\nsignificantly increased.Â </p>\n<p>Here are some example outputs:</p>",
        "id": 294756881,
        "sender_full_name": "Email Gateway",
        "timestamp": 1661197905
    },
    {
        "content": "<p>From: Mathias Fleury &lt;<a href=\"mailto:mathias.fleury12@gmail.com\">mathias.fleury12@gmail.com</a>&gt;<br>\nHi Peter,</p>\n<p>I think I have found the problem for Z3, but I cannot explain why it would appear now.</p>\n<p>SMT (directly or via Sledgehammer) starts z3 with a timeout of XXs. However, SMT sees the answer \"timeout\" (as given by Z3) an error. So basically, it a timing issue: if SMT kills the call to the solver, everything is fine. Otherwise, it fails.</p>\n<p>I don't know what happens for CVC4, I have not managed to reproduce the issue.</p>\n<p>Can you try the attached patch?</p>\n<p>Thanks,<br>\nMathias<br>\n<a href=\"/user_uploads/14278/cPBvrHrYsUaGqNIY9B5a4rGM/support_timeout\">support_timeout</a></p>",
        "id": 294756954,
        "sender_full_name": "Email Gateway",
        "timestamp": 1661197923
    }
]